joint_limits:
  lwr/lwr_4_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  lwr/lwr_6_joint:
    has_velocity_limits: true
    max_velocity: 1.96349540849
    has_acceleration_limits: false
    max_acceleration: 0
  lwr/lwr_3_joint:
    has_velocity_limits: true
    max_velocity: 1.96349540849
    has_acceleration_limits: false
    max_acceleration: 0
  lwr/lwr_5_joint:
    has_velocity_limits: true
    max_velocity: 1.96349540849
    has_acceleration_limits: false
    max_acceleration: 0
  lwr/lwr_1_joint:
    has_velocity_limits: true
    max_velocity: 1.96349540849
    has_acceleration_limits: false
    max_acceleration: 0
  lwr/lwr_2_joint:
    has_velocity_limits: true
    max_velocity: 1.96349540849
    has_acceleration_limits: false
    max_acceleration: 0
  lwr/lwr_0_joint:
    has_velocity_limits: true
    max_velocity: 1.96349540849
    has_acceleration_limits: false
    max_acceleration: 0