arm:
#  kinematic_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: lwr_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.003
  kinematics_solver_timeout: 0.005
